@startuml avaliacaoforca
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(profissionalDeSaude, "Profissional de Saúde", "Médicos, enfermeiros, ACS e ETC")

System_Boundary(aavaliacaoforca, "Projeto Avaliação da força de trabalho") {
    System(IDSaude, "IDSaúde", "Keycloak", $link="https://raw.githubusercontent.com/victorMagalhaesPacheco/plantuml-arquitetura-sistemas-forcadetrabalho/main/out/forcadetrabalho/avaliacaoforca.svg")
    System(mapadasaude, "Mapa da Saúde", "Mapeamento das instituições e profissionais de saúde")
    System(IDSaudeapi, "ID Saúde - API", "Extensão do ID Saúde keycloak")
    System(isus, "iSUS", "Aplicativo para profissionais de Saúde")
    System(qualiquiz, "QualiQuiz", "Ferramenta para avaliações por competências dos profissionais de saúde")
    Rel(profissionalDeSaude, isus, "Acessa o aplicativo", "Android ou ios")
    Rel(profissionalDeSaude, mapadasaude, "Acessa ao mapa da Saúde, perfil, espaços e editais", "HTTPS")
    Rel(profissionalDeSaude, IDSaude, "Acessa o IDSaúde - cadastro, minha conta, consentimentos", "HTTPS")
    Rel(profissionalDeSaude, qualiquiz, "Acessa o QualiQuiz", "HTTPS, Moodle")

    Rel(mapadasaude, IDSaude, "Autenticação (browser)", "OPENID CONNECT");
    Rel(isus, IDSaude, "Recuperação de senha", "HTTPS");
    Rel(IDSaudeapi, IDSaude, "Extensão da API do IDSaude", "RestFul");
    Rel(isus, IDSaudeapi, "Valida se CPF/email está cadastro", "RestFul");
    Rel(isus, mapadasaude, "Integração Taxonomias", "RestFul");
}

System_Boundary(coronavirus, "coronavirus.ceara.gov.br") {
    System_Ext(wordpressapi, "WordPress API", "Gerenciamento de categorias e projetos")
}

Rel(isus, wordpressapi, "Integração categorias e projetos", "RestFul");

@enduml